/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffee.ordering.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jayde
 */
public class AdminFrame extends javax.swing.JFrame {

    Connection con;
    
    public AdminFrame() {
        initComponents();
        usersInternalFrame.setVisible(false);
        orderInternalFrame.setVisible(false);
        String url="jdbc:MySQL://localhost:3306/java_user_database";
        String user="root";
        String pass="";
        try{
            con = DriverManager.getConnection(url,user,pass); // Assign to 'con'
        }catch(Exception ex){
            System.out.println("Error : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoutBtn = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        orderSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        order_status = new javax.swing.JTable();
        usersInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        orderInternalFrame = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");
        setPreferredSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(null);

        LogoutBtn.setText("LOGOUT");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutBtn);
        LogoutBtn.setBounds(32, 549, 77, 23);

        user.setText("jLabel1");
        getContentPane().add(user);
        user.setBounds(50, 50, 157, 99);

        jButton1.setText("usersButton");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 270, 110, 23);

        orderSearch.setText("orderSearchButton");
        orderSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSearchActionPerformed(evt);
            }
        });
        getContentPane().add(orderSearch);
        orderSearch.setBounds(50, 330, 130, 23);

        order_status.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "user_id", "full name", "payment type", "status"
            }
        ));
        jScrollPane3.setViewportView(order_status);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(260, 160, 410, 270);

        usersInternalFrame.setTitle("USERS");
        usersInternalFrame.setVisible(true);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "First Name", "Last Name", "Email", "Username", "Password", "User Type"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        javax.swing.GroupLayout usersInternalFrameLayout = new javax.swing.GroupLayout(usersInternalFrame.getContentPane());
        usersInternalFrame.getContentPane().setLayout(usersInternalFrameLayout);
        usersInternalFrameLayout.setHorizontalGroup(
            usersInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        usersInternalFrameLayout.setVerticalGroup(
            usersInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersInternalFrameLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        getContentPane().add(usersInternalFrame);
        usersInternalFrame.setBounds(0, 0, 630, 370);

        orderInternalFrame.setTitle("Order Summary");
        orderInternalFrame.setVisible(true);

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order", "Size", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        javax.swing.GroupLayout orderInternalFrameLayout = new javax.swing.GroupLayout(orderInternalFrame.getContentPane());
        orderInternalFrame.getContentPane().setLayout(orderInternalFrameLayout);
        orderInternalFrameLayout.setHorizontalGroup(
            orderInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        orderInternalFrameLayout.setVerticalGroup(
            orderInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        getContentPane().add(orderInternalFrame);
        orderInternalFrame.setBounds(0, 0, 590, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usersInternalFrame.setVisible(!usersInternalFrame.isVisible());
        String sql= "SELECT * FROM user";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
            model.setRowCount(0);
            while(rs.next()) {
                model.addRow(new String[]{rs.getString(1),rs.getString(6), rs.getString(7), rs.getString(2), rs.getString(8), rs.getString(3), rs.getString(4)});
            }
        }catch(Exception e){
            System.out.println("Error : " +e.getMessage());
        }
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void orderSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSearchActionPerformed
        orderInternalFrame.setVisible(!orderInternalFrame.isVisible());
        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter User ID:");
        if (input != null && !input.trim().isEmpty()) {
            try {
                int userId = Integer.parseInt(input.trim());
                String sql = "SELECT item_name, size, quantity, price FROM orders WHERE user_id = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, userId);
                ResultSet rs = pst.executeQuery();

                DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
                model.setRowCount(0);

                boolean hasData = false;
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("item_name"),
                        rs.getString("size"),
                        rs.getInt("quantity"),
                        rs.getDouble("price")
                    });
                    hasData = true;
                }

                if (!hasData) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No orders found for User ID: " + userId);
                }

                rs.close();
                pst.close();
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid User ID format.");
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error retrieving orders: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_orderSearchActionPerformed
    
    public void setUser(String name){
        user.setText(name);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JInternalFrame orderInternalFrame;
    private javax.swing.JButton orderSearch;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable order_status;
    private javax.swing.JTable tblUsers;
    private javax.swing.JLabel user;
    private javax.swing.JInternalFrame usersInternalFrame;
    // End of variables declaration//GEN-END:variables
}
