/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coffee.ordering.system;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author jayde
 */
public class AdminFrame extends javax.swing.JFrame {

    Connection con;
    
    public AdminFrame() {
        initComponents();
           
        usersInternalFrame.setVisible(false);
        orderInternalFrame.setVisible(false);
        
        int homeIconSize = 16; // Or any size that fits well
        totalAccounts.setIcon(getScaledIcon("/images/people.png", homeIconSize));
        totalAccounts.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        totalAccounts.setIconTextGap(10); // Optional: spacing between icon and text
        totalSales.setIcon(getScaledIcon("/images/sales.png", homeIconSize));
        totalSales.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        totalSales.setIconTextGap(10); // Optional: spacing between icon and text        
        totalOrders.setIcon(getScaledIcon("/images/order.png", homeIconSize));
        totalOrders.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        totalOrders.setIconTextGap(10); // Optional: spacing between icon and text       
        LogoutBtn.setIcon(getScaledIcon("/images/logout.png", homeIconSize));
        LogoutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        LogoutBtn.setIconTextGap(1); // Optional: spacing between icon and text  
        jButton1.setIcon(getScaledIcon("/images/search-user.png", homeIconSize));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        jButton1.setIconTextGap(1); // Optional: spacing between icon and text  
        orderSearch.setIcon(getScaledIcon("/images/tracking.png", homeIconSize));
        orderSearch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        orderSearch.setIconTextGap(1); // Optional: spacing between icon and text  
        completeOrder.setIcon(getScaledIcon("/images/complete.png", homeIconSize));
        completeOrder.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        completeOrder.setIconTextGap(1); // Optional: spacing between icon and text  
        deleteCompletedOrder.setIcon(getScaledIcon("/images/delete-product.png", homeIconSize));
        deleteCompletedOrder.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        deleteCompletedOrder.setIconTextGap(1); // Optional: spacing between icon and text    
        cancelOrder.setIcon(getScaledIcon("/images/cancel.png", homeIconSize));
        cancelOrder.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT); // Optional: text to the right of icon
        cancelOrder.setIconTextGap(1); // Optional: spacing between icon and text          
        
        String url="jdbc:MySQL://localhost:3306/java_user_database";
        String user="root";
        String pass="";
        try{
            con = DriverManager.getConnection(url,user,pass); // Assign to 'con'
        }catch(Exception ex){
            System.out.println("Error : " + ex.getMessage());
        }
        loadOrderSummary();
        loadAdminStats();
    }

    private ImageIcon getScaledIcon(String path, int size) {
    ImageIcon icon = new ImageIcon(getClass().getResource(path));
    Image img = icon.getImage().getScaledInstance(size, size, Image.SCALE_SMOOTH);
    return new ImageIcon(img);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usersInternalFrame = new javax.swing.JInternalFrame();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        orderInternalFrame = new javax.swing.JInternalFrame();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        LogoutBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        orderSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        order_status = new javax.swing.JTable();
        completeOrder = new javax.swing.JButton();
        deleteCompletedOrder = new javax.swing.JButton();
        cancelOrder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        totalSales = new javax.swing.JLabel();
        showTotalSales = new javax.swing.JLabel();
        showTotalOrders = new javax.swing.JLabel();
        totalOrders = new javax.swing.JLabel();
        showTotalAccounts = new javax.swing.JLabel();
        totalAccounts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN");
        setBackground(new java.awt.Color(239, 233, 233));
        setMaximumSize(new java.awt.Dimension(920, 610));
        setMinimumSize(new java.awt.Dimension(920, 610));
        setPreferredSize(new java.awt.Dimension(920, 610));
        setResizable(false);
        getContentPane().setLayout(null);

        usersInternalFrame.setBackground(new java.awt.Color(239, 233, 233));
        usersInternalFrame.setTitle("USERS");
        usersInternalFrame.setVisible(true);
        usersInternalFrame.getContentPane().setLayout(null);

        jButton3.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        usersInternalFrame.getContentPane().add(jButton3);
        jButton3.setBounds(250, 300, 80, 26);

        tblUsers.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User ID", "First Name", "Last Name", "Email", "Username", "Password", "User Type"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        usersInternalFrame.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 7, 570, 280);

        getContentPane().add(usersInternalFrame);
        usersInternalFrame.setBounds(140, 70, 600, 380);

        orderInternalFrame.setBackground(new java.awt.Color(239, 233, 233));
        orderInternalFrame.setTitle("Order Summary");
        orderInternalFrame.setVisible(true);
        orderInternalFrame.getContentPane().setLayout(null);

        jButton2.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        orderInternalFrame.getContentPane().add(jButton2);
        jButton2.setBounds(250, 400, 80, 26);

        orderTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order", "Size", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        orderInternalFrame.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(8, 24, 570, 360);

        getContentPane().add(orderInternalFrame);
        orderInternalFrame.setBounds(140, 40, 600, 480);

        LogoutBtn.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        LogoutBtn.setText("LOGOUT");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LogoutBtn);
        LogoutBtn.setBounds(20, 520, 100, 26);

        jButton1.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        jButton1.setText("Search Users");
        jButton1.setActionCommand("Users List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 520, 130, 26);

        orderSearch.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        orderSearch.setText("Search Orders");
        orderSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSearchActionPerformed(evt);
            }
        });
        getContentPane().add(orderSearch);
        orderSearch.setBounds(270, 520, 130, 26);

        order_status.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "user_id", "Full Name", "Payment Type", "Payment Method", "Total", "City", "Address", "Number", "Status"
            }
        ));
        jScrollPane3.setViewportView(order_status);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 150, 870, 350);

        completeOrder.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        completeOrder.setText("Complete Order");
        completeOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeOrderActionPerformed(evt);
            }
        });
        getContentPane().add(completeOrder);
        completeOrder.setBounds(410, 520, 140, 26);

        deleteCompletedOrder.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        deleteCompletedOrder.setText("Delete Completed Order");
        deleteCompletedOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCompletedOrderActionPerformed(evt);
            }
        });
        getContentPane().add(deleteCompletedOrder);
        deleteCompletedOrder.setBounds(560, 520, 190, 26);

        cancelOrder.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        cancelOrder.setText("Cancel Order");
        cancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOrderActionPerformed(evt);
            }
        });
        getContentPane().add(cancelOrder);
        cancelOrder.setBounds(760, 520, 130, 26);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Welcome Admin!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 20, 205, 37);

        user.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        user.setText("full name ");
        getContentPane().add(user);
        user.setBounds(20, 60, 200, 22);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        totalSales.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        totalSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalSales.setText("Total Sales");
        jPanel1.add(totalSales);
        totalSales.setBounds(390, 20, 150, 19);

        showTotalSales.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        showTotalSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showTotalSales.setText("total");
        jPanel1.add(showTotalSales);
        showTotalSales.setBounds(430, 50, 90, 19);

        showTotalOrders.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        showTotalOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showTotalOrders.setText("total");
        jPanel1.add(showTotalOrders);
        showTotalOrders.setBounds(230, 50, 90, 19);

        totalOrders.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        totalOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalOrders.setText("Total Orders");
        jPanel1.add(totalOrders);
        totalOrders.setBounds(200, 20, 150, 19);

        showTotalAccounts.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        showTotalAccounts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showTotalAccounts.setText("total");
        jPanel1.add(showTotalAccounts);
        showTotalAccounts.setBounds(40, 50, 70, 19);

        totalAccounts.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        totalAccounts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAccounts.setText("Total Accounts");
        jPanel1.add(totalAccounts);
        totalAccounts.setBounds(10, 20, 150, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(340, 20, 550, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        int choice = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout Confirmation",
        JOptionPane.YES_NO_OPTION
        );

        if (choice == JOptionPane.YES_OPTION) {
            Login loginFrame = new Login();
            loginFrame.setVisible(true);
            loginFrame.pack();
            loginFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usersInternalFrame.setVisible(!usersInternalFrame.isVisible());
        String sql= "SELECT * FROM user";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tblUsers.getModel();
            model.setRowCount(0);
            while(rs.next()) {
                model.addRow(new String[]{rs.getString(1),rs.getString(6), rs.getString(5), rs.getString(2), rs.getString(8), rs.getString(3), rs.getString(4)});
            }
        }catch(Exception e){
            System.out.println("Error : " +e.getMessage());
        }
   
    }//GEN-LAST:event_jButton1ActionPerformed
    private void loadAdminStats() {
        try {
            // TOTAL ACCOUNTS
            String sqlAccounts = "SELECT COUNT(*) AS total_accounts FROM user";
            PreparedStatement pstAccounts = con.prepareStatement(sqlAccounts);
            ResultSet rsAccounts = pstAccounts.executeQuery();
            if (rsAccounts.next()) {
                int totalAccounts = rsAccounts.getInt("total_accounts");
                showTotalAccounts.setText(String.valueOf(totalAccounts)); // <== your label
            }
            rsAccounts.close();
            pstAccounts.close();

            // TOTAL ORDERS (count DISTINCT user_ids in orders)
            String sqlOrders = "SELECT COUNT(DISTINCT user_id) AS total_orders FROM orders";
            PreparedStatement pstOrders = con.prepareStatement(sqlOrders);
            ResultSet rsOrders = pstOrders.executeQuery();
            if (rsOrders.next()) {
                int totalOrders = rsOrders.getInt("total_orders");
                showTotalOrders.setText(String.valueOf(totalOrders)); // <== your label
            }
            rsOrders.close();
            pstOrders.close();

            // TOTAL SALES
            String sqlSales = "SELECT SUM(total_amount) AS total_sales FROM order_summary";
            PreparedStatement pstSales = con.prepareStatement(sqlSales);
            ResultSet rsSales = pstSales.executeQuery();
            if (rsSales.next()) {
                double totalSales = rsSales.getDouble("total_sales");
                showTotalSales.setText("₱" + String.format("%.2f", totalSales)); // <== your label
            }
            rsSales.close();
            pstSales.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading dashboard stats: " + e.getMessage());
        }
    }
    


    private void loadOrderSummary() {
        DefaultTableModel model = (DefaultTableModel) order_status.getModel();
        model.setRowCount(0); // clear existing rows

        String sql = "SELECT user_id, full_name, payment_method, payment_type, address, total_amount, city, phone_number, status FROM order_summary";

        try {
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("user_id"),
                    rs.getString("full_name"),
                    rs.getString("payment_method"),
                    rs.getString("payment_type"),
                    rs.getString("address"),
                    "₱" + String.format("%.2f", rs.getDouble("total_amount")),
                    rs.getString("city"),
                    rs.getString("phone_number"),
                    rs.getString("status")
                };
                model.addRow(row);
            }

            rs.close();
            pst.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading order summary: " + e.getMessage());
        }
    }
    private void orderSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSearchActionPerformed

        String input = javax.swing.JOptionPane.showInputDialog(this, "Enter User ID:");
        if (input != null && !input.trim().isEmpty()) {
            try {
                int userId = Integer.parseInt(input.trim());
                String sql = "SELECT item_name, size, quantity, price FROM orders WHERE user_id = ?";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setInt(1, userId);
                ResultSet rs = pst.executeQuery();
                
                orderInternalFrame.setVisible(true);
                DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
                model.setRowCount(0);
                
                
                boolean hasData = false;
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("item_name"),
                        rs.getString("size"),
                        rs.getInt("quantity"),
                        rs.getDouble("price")
                    });
                    hasData = true;
                }

                if (!hasData) {
                    javax.swing.JOptionPane.showMessageDialog(this, "No orders found for User ID: " + userId);
                }

                rs.close();
                pst.close();
            } catch (NumberFormatException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Invalid User ID format.");
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error retrieving orders: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_orderSearchActionPerformed

    private void completeOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeOrderActionPerformed
        String input = JOptionPane.showInputDialog(this, "Enter the User ID for completed orders:");
        if (input == null || input.trim().isEmpty()) {
            return; // user cancelled or left it blank
        }

        int userId;

        try {
            userId = Integer.parseInt(input.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid user ID. Please enter a number.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Have you completed the order for User ID: " + userId + "?",
            "Confirm Completion",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            String sql = "UPDATE order_summary SET status = 'Completed' WHERE user_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, userId);
            int updatedRows = pst.executeUpdate();

            if (updatedRows > 0) {
                JOptionPane.showMessageDialog(this, "Order(s) marked as completed.");
                loadOrderSummary(); // ✅ Refresh the table
            } else {
                JOptionPane.showMessageDialog(this, "No orders found for that user.");
            }

            pst.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_completeOrderActionPerformed

    private void deleteCompletedOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCompletedOrderActionPerformed
        String input = JOptionPane.showInputDialog(this, "Enter the User ID to delete completed order:");

        if (input == null || input.trim().isEmpty()) {
            return; // User cancelled or empty input
        }

        int userId;
        try {
            userId = Integer.parseInt(input.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid user ID. Please enter a number.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Do you want to delete the completed order for User ID: " + userId + "?",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // First check if the order exists and is completed
            String checkSql = "SELECT status FROM order_summary WHERE user_id = ?";
            PreparedStatement checkPst = con.prepareStatement(checkSql);
            checkPst.setInt(1, userId);
            ResultSet rs = checkPst.executeQuery();

            if (rs.next()) {
                String status = rs.getString("status");
                if ("Completed".equalsIgnoreCase(status)) {
                    // Delete the order
                    String deleteSql = "DELETE FROM order_summary WHERE user_id = ?";
                    PreparedStatement deletePst = con.prepareStatement(deleteSql);
                    deletePst.setInt(1, userId);
                    deletePst.executeUpdate();
                    deletePst.close();

                    JOptionPane.showMessageDialog(this, "Completed order for user ID " + userId + " has been deleted.");
                    loadOrderSummary(); // Refresh table
                } else {
                    JOptionPane.showMessageDialog(this, "Order status is not 'Completed'. Cannot delete.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No order found for that user ID.");
            }

            rs.close();
            checkPst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_deleteCompletedOrderActionPerformed

    private void cancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOrderActionPerformed
        String input = JOptionPane.showInputDialog(this, "Enter the User ID to cancel the order:");

        if (input == null || input.trim().isEmpty()) {
            return; // User cancelled or empty input
        }

        int userId;
        try {
            userId = Integer.parseInt(input.trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid user ID. Please enter a number.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to cancel the order for User ID: " + userId + "?",
            "Confirm Cancellation",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // First check if an order exists
            String checkSql = "SELECT * FROM order_summary WHERE user_id = ?";
            PreparedStatement checkPst = con.prepareStatement(checkSql);
            checkPst.setInt(1, userId);
            ResultSet rs = checkPst.executeQuery();

            if (rs.next()) {
                // Delete from order_summary
                String deleteSummarySql = "DELETE FROM order_summary WHERE user_id = ?";
                PreparedStatement deleteSummaryPst = con.prepareStatement(deleteSummarySql);
                deleteSummaryPst.setInt(1, userId);
                deleteSummaryPst.executeUpdate();
                deleteSummaryPst.close();

                // Optional: Also delete from orders table
                String deleteOrdersSql = "DELETE FROM orders WHERE user_id = ?";
                PreparedStatement deleteOrdersPst = con.prepareStatement(deleteOrdersSql);
                deleteOrdersPst.setInt(1, userId);
                deleteOrdersPst.executeUpdate();
                deleteOrdersPst.close();

                JOptionPane.showMessageDialog(this, "Order for user ID " + userId + " has been cancelled.");
                loadOrderSummary(); // Refresh table

            } else {
                JOptionPane.showMessageDialog(this, "No order found for that user ID.");
            }

            rs.close();
            checkPst.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        }
    }//GEN-LAST:event_cancelOrderActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        orderInternalFrame.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        usersInternalFrame.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    public void setUser(String name){
        user.setText(name);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton cancelOrder;
    private javax.swing.JButton completeOrder;
    private javax.swing.JButton deleteCompletedOrder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JInternalFrame orderInternalFrame;
    private javax.swing.JButton orderSearch;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable order_status;
    private javax.swing.JLabel showTotalAccounts;
    private javax.swing.JLabel showTotalOrders;
    private javax.swing.JLabel showTotalSales;
    private javax.swing.JTable tblUsers;
    private javax.swing.JLabel totalAccounts;
    private javax.swing.JLabel totalOrders;
    private javax.swing.JLabel totalSales;
    private javax.swing.JLabel user;
    private javax.swing.JInternalFrame usersInternalFrame;
    // End of variables declaration//GEN-END:variables

}
